version: '3'
services:
  etherpad:
    # image: tvelocity/etherpad-lite
    build: .
    depends_on:
      - db
    environment:
      ETHERPAD_DB_HOST: db
      ETHERPAD_DB_PASSWORD: password
      # ETHERPAD_ADMIN_USER: admin
      # ETHERPAD_ADMIN_PASSWORD: password
    ports:
      - "9001:9001"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
